# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}{,/**/*}"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/app.js"
    - "src/assets/js/canvasParticles.js"
    - "src/assets/js/dragDropTouch.js"
    - "src/assets/js/javascriptToDo.js"
    - "src/assets/js/javascriptTetris.js"
    - "src/assets/js/javascript30/1-drum-kit.js"
    - "src/assets/js/javascript30/2-clock.js"
    - "src/assets/js/javascript30/3-update-css-variables.js"
    - "src/assets/js/javascript30/4-array-cardio-day-1.js"
    - "src/assets/js/javascript30/5-flex-panel-gallery.js"
    - "src/assets/js/javascript30/6-type-ahead.js"
    - "src/assets/js/javascript30/7-array-cardio-day-2.js"
    - "src/assets/js/javascript30/8-fun-with-html5-canvas.js"
    - "src/assets/js/javascript30/9-dev-tools-domination.js"
    - "src/assets/js/javascript30/10-hold-shift-and-check-checkboxes.js"
    - "src/assets/js/javascript30/11-custom-video-player.js"
    - "src/assets/js/javascript30/12-key-sequence-detection.js"
    - "src/assets/js/javascript30/13-slide-in-on-scroll.js"
    - "src/assets/js/javascript30/14-javaScript-references-vs-copying.js"
    - "src/assets/js/javascript30/15-local-storage.js"
    - "src/assets/js/javascript30/16-mouse-move-shadow.js"
    - "src/assets/js/javascript30/17-sort-without-articles.js"
    - "src/assets/js/javascript30/18-adding-up-times-with-reduce.js"
    - "src/assets/js/javascript30/19-webcam-fun.js"
    - "src/assets/js/javascript30/20-speech-detection.js"
    - "src/assets/js/javascript30/21-geolocation.js"
    - "src/assets/js/javascript30/22-follow-along-link-highlighter.js"
    - "src/assets/js/javascript30/23-speech-synthesis.js"
    - "src/assets/js/javascript30/24-sticky-nav.js"
    - "src/assets/js/javascript30/25-event-capture-propagation-bubbling-and-once.js"
    - "src/assets/js/javascript30/26-stripe-follow-along-nav.js"
    - "src/assets/js/javascript30/27-click-and-drag.js"
    - "src/assets/js/javascript30/28-video-speed-controller.js"
    - "src/assets/js/javascript30/29-countdown-timer.js"
    - "src/assets/js/javascript30/30-whack-a-mole.js"