# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}{,/**/*}"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/app.js"
    - "src/assets/js/canvasParticles.js"
    - "src/assets/js/dragDropTouch.js"
    - "src/assets/js/javascriptToDo.js"
    - "src/assets/js/javascriptTetris.js"
    - "src/assets/js/javascript30/1-drum-kit.js"
    - "src/assets/js/javascript30/2-clock.js"
    - "src/assets/js/javascript30/3-update-css-variables.js"
    - "src/assets/js/javascript30/4.js"
    - "src/assets/js/javascript30/5.js"
    - "src/assets/js/javascript30/6.js"
    - "src/assets/js/javascript30/7.js"
    - "src/assets/js/javascript30/8.js"
    - "src/assets/js/javascript30/9.js"
    - "src/assets/js/javascript30/10.js"
    - "src/assets/js/javascript30/11.js"
    - "src/assets/js/javascript30/12.js"
    - "src/assets/js/javascript30/13.js"
    - "src/assets/js/javascript30/14.js"
    - "src/assets/js/javascript30/15.js"
    - "src/assets/js/javascript30/16.js"
    - "src/assets/js/javascript30/17.js"
    - "src/assets/js/javascript30/18.js"
    - "src/assets/js/javascript30/19.js"
    - "src/assets/js/javascript30/20.js"
    - "src/assets/js/javascript30/21.js"
    - "src/assets/js/javascript30/22.js"
    - "src/assets/js/javascript30/23.js"
    - "src/assets/js/javascript30/24.js"
    - "src/assets/js/javascript30/25.js"
    - "src/assets/js/javascript30/26.js"
    - "src/assets/js/javascript30/27.js"
    - "src/assets/js/javascript30/28.js"
    - "src/assets/js/javascript30/29.js"
    - "src/assets/js/javascript30/30.js"